services:
  mysql:
    image: mysql:8.0
    container_name: itau-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itau_cp
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20